theme = "catppuccin_macchiato"

[editor]
mouse = false
auto-completion = true
preview-completion-insert = false
completion-timeout = 5
auto-format = true
idle-timeout = 100
soft-wrap.enable = true
line-number = "relative"
cursorline = true
continue-comments = false
color-modes = true
end-of-line-diagnostics = "error"
# jump-label-alphabet = "ntehosurpdlmia"
jump-label-alphabet = "hsaterinodulpw"

[editor.lsp]
snippets = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "none"

[editor.indent-guides]
render = true

[editor.search]
# smart-case = false

# [editor.soft-wrap]
# enable = true

# [editor.inline-diagnostics]
# cursor-line = "warning"
# other-lines = "error"



[keys.normal]
"esc" = "collapse_selection"
"H" = "@;vgs<esc>"
"L" = "@;vgl<esc>"
